# No todo empezó en octubre de 2023

## Breve historia de la colonización de Palestina

Lineas de tiempo poniendo los diferentes eventos marcantes

Que queremos mostrar

-   la expulsion de los palestinos en 1947/48

Mapas y graficas

En *Comprendre la Palestine*

Grafica Particion territoriale de la palestine mandataire p31

En *Israel le nouvel apartheid* **2013**

cartes perte du territoire de 1947 a 2013 p145

Lineas de tiempo poniendo los diferentes eventos marcantes

En **Atlas des palestiniens (2017)**

Refugies et diaspora

Mapa/Grafica

Les palestiniens dans de monde p47
Les refugies arabes en 1948

Les camps de refugiés p 50

**Gaza JP Filliu 2012**

p64 resumen del plan de partition

**The Palestine Nakba 2012**

Memoricide (cambio toponimia, reforestación pueblos palestinos, destrucción archivos

*Palestine, plus d un siecle de depossession 2024*

**La Palestine assassinée**

avant propos p 12

Resolucion 181 p34

**La Nakba**
Carte 6 repartition de la population (bubble map)

Tabla 2 immigracion juidía 1920 a 1949

offensive sioniste p 11

Tabla 3 : Raisons de l’exode des quelque 370 000 Palestiniens qui sont partis avant le 1er juin 1948

Texte les consequences de la guerre

**La conquete de la palestine 2024**

Buena síntesis Nakba

conclusions
