project:
  type: book
  # para html
  output-dir: docs

book:
  title: "Mapas y gráficas contra el genocidio"
  output-file: "Palestine"
  author: "JF Mas, A Pérez Vega, JV Solórzano"
  date: last-modified
  page-navigation: true
  sidebar:
    style: docked
    background: light
  # cover-image: cover.png
  chapters:
    - index.qmd
    - 0.intro.qmd
    - 1.pre2023.qmd
    - 2.ocupacion.qmd
    - 3.apartheid.qmd
    - 4.gaza.qmd
    - 5.genocidio.qmd
    - 6.complicidad.qmd
    - references.qmd
  search: true
  # repo-url: https://github.com/jjallaire/hopr/
  repo-actions: [edit]
  downloads: [pdf, epub]
  page-footer: 
    left: "Copyright 2025, JFM, APV, JVS" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

bibliography: references.bib
csl: citestyle.csl
highlight-style: pygments

format:
  html:
    theme: flatly
    number-sections: true
    css: style.css
  # Faltan algunos paquetes para exportar a pdf  
  # pdf:
  #   documentclass: scrreprt

editor: visual

